### ISSUE TITLE
Is the database mounted?

### ISSUE THREAD

**Issue by flitzcore** [firmanJS/Dockerize-Codeigniter-With-docker-compose#1]
Permisi tanya, di contoh ini apakah database sql nya bakalan ke reset setiap docker composenya di up? ataukah bisa di mount ke local?

**Comment by firmanJS** [comment]
> Permisi tanya, di contoh ini apakah database sql nya bakalan ke reset setiap docker composenya di up? ataukah bisa di mount ke local?

akan tereset sepertinya karena belum termounting
